version: '3'
services:
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
     - .docker/mysql:/var/lib/mysql